### PR TITLE
secureiowa test

### PR DESCRIPTION
**Pull request by JeffreyLMelvin**

### CODE REVIEW

**Comment by AetherDeity** [comment]
## Raven
Number of Findings: 2
* Watched keyword ```password``` in ```sensitive.py``` line(s) ['4-5'] added
* Watched keyword ```encryption``` in ```sensitive.py``` line(s) ['1'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by AetherDeity** [comment]
@tweek

**Comment by AetherDeity** [comment]
@tweek

**Comment by AetherDeity** [comment]
@tweek

**Comment by JeffreyLMelvin** [comment]
@tweek

**Comment by JeffreyLMelvin** [comment]
## Raven

Number of Findings: 2
- Watched keyword `password` in `sensitive.py` line(s) ['4-5'] added
- Watched keyword `encrypt` in `sensitive.py` line(s) ['1-2'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

## Osprey

SourceClear Results:
- High Vulnerabilities: 0
- Medium Vulnerabilities: 0
- Low Vulnerabilities: 0

**Pull request closed without merging**
